/**
 * What `wilanis describe` and `wilanis ls` say of scenarios (RFC 0018, step 8), on a copy of the example the
 * recorder and `fuzz --edges` have written into, with a scenario of each other kind planted beside: a fuzzed run, one
 * kept by hand, and a branch no input reaches. A scenario says what it proves before what it ran, and which command
 * rewrites it; a trigger says how many scenarios replay it and who wrote them.
 */
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { type LoadResult, loadTree, nodesOf, type ScenarioDoc, stubsOf } from '@wilanis/core';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { describe as describeDoc, fuzz, ls, RECORDED, rehearse } from '../src/index.js';
import { copyOfExample, INCLUDES, PLUGINS } from './example-harness.js';

const GET_CUSTOMER = '@features/customers/edge/get-customer.trigger.json';
const MISSING = `${RECORDED}/customers.get-customer/customers.get-row.outcome.noCustomer.scenario.json`;
const ANONYMOUS = `${RECORDED}/policies/access.employees-only/access.require-employee.isEmployee.anonymous.scenario.json`;
const EMPTY_ID = 'scenarios/edges/customers.get-customer/id.empty.scenario.json';
const read = (path: string) => JSON.parse(readFileSync(path, 'utf8'));

/** The body `describe` prints for one document: what follows the blank line after its description. */
const body = (load: LoadResult, path: string) => {
  const lines = describeDoc(load, path).split('\n');
  return lines.slice(lines.indexOf('') + 1);
};

let dir: string;
let load: LoadResult;

/** A recorded scenario with every answer and stub its answers file holds written in place of the digest. */
function inline(sc: ScenarioDoc, answers: Parameters<typeof nodesOf>[1]): ScenarioDoc {
  const { sharedStubs: _, ...rest } = sc;
  const nodes = nodesOf(sc, answers).nodes;
  return { ...rest, stubs: stubsOf(sc, answers).stubs, expect: { ...sc.expect, nodes } };
}

/** Write one scenario into the copy, at a path below its root. */
function plant(file: string, doc: unknown) {
  mkdirSync(join(dir, file, '..'), { recursive: true });
  writeFileSync(join(dir, file), JSON.stringify(doc, null, 2));
}

beforeAll(async () => {
  dir = copyOfExample();
  await rehearse(loadTree(dir, PLUGINS, INCLUDES), { record: RECORDED });
  await fuzz(loadTree(dir, PLUGINS, INCLUDES), { edges: true });
  const missing = read(join(dir, MISSING));
  // the same run kept by a person, and as plain fuzz would have written it: each with its answers inline, since
  // neither has an answers file
  const { generated: _, ...kept } = inline(missing, read(join(dir, RECORDED, 'answers.json')));
  plant('scenarios/first-miss.scenario.json', { ...kept, description: 'A customer that is not there, kept by hand.' });
  plant('scenarios/fuzz/get-customer.1.scenario.json', { ...kept, generated: 'fuzz' });
  // a branch no input reaches, as the recorder writes one: nothing to run, so no input and no stubs
  plant(`${RECORDED}/customers.list-customers/customers.list-rows.outcome.customers.scenario.json`, {
    $schema: missing.$schema,
    description: 'list-customers: no input reaches it.',
    generated: 'rehearse',
    trigger: '@features/customers/edge/list-customers.trigger.json',
    branch: {
      graph: '@features/customers/data/list-rows.graph.json',
      node: 'outcome',
      when: 'status == 200 && has(body)',
      to: 'customers',
    },
    seed: 1,
    expect: { status: 'unreachable', nodes: {}, unreachable: 'the rules before it already cover every input' },
  });
  load = loadTree(dir, PLUGINS, INCLUDES);
}, 60_000);

afterAll(() => rmSync(dir, { recursive: true, force: true }));

describe('wilanis describe: a scenario says what it proves', () => {
  it('prints the trigger, the branch, the seed, the refusal it expects, how each switch routed, and who rewrites it', () => {
    expect(body(load, `@${MISSING}`)).toEqual([
      `drives  ${GET_CUSTOMER}`,
      "proves  get-row 'outcome' when status == 404 → noCustomer",
      'seed    1',
      'expects failed as missing',
      '    op.outcome → noCustomer',
      `answers @${RECORDED}/answers.json`,
      'generated by wilanis rehearse --record: regenerate, do not edit',
    ]);
  });

  it("names the policy a decision is replayed through, and says the else as 'otherwise'", () => {
    const said = body(load, `@${ANONYMOUS}`);
    expect(said.slice(0, 3)).toEqual([
      'drives  @features/customers/edge/delete-customer.trigger.json',
      "policy  @features/access/edge/employees-only.policy.json  (its decide, fired under the trigger's kind in place of the trigger's fire)",
      "proves  require-employee 'isEmployee' otherwise → anonymous",
    ]);
    expect(said).toContain('expects failed as anonymous');
  });

  it('says of an edge that fuzz --edges rewrites it, and proves no branch', () => {
    const said = body(load, `@${EMPTY_ID}`);
    expect(said.some(line => line.startsWith('proves'))).toBe(false);
    expect(said.at(-1)).toBe('generated by wilanis fuzz --edges: regenerate, do not edit');
    expect(body(load, '@scenarios/fuzz/get-customer.1.scenario.json').at(-1)).toBe(
      'generated by wilanis fuzz: regenerate, do not edit',
    );
  });

  it('says why a branch is unreachable, and routes nothing, since nothing ran', () => {
    expect(
      body(load, `@${RECORDED}/customers.list-customers/customers.list-rows.outcome.customers.scenario.json`),
    ).toEqual([
      'drives  @features/customers/edge/list-customers.trigger.json',
      "proves  list-rows 'outcome' when status == 200 && has(body) → customers",
      'seed    1',
      'expects unreachable -- the rules before it already cover every input',
      'generated by wilanis rehearse --record: regenerate, do not edit',
    ]);
  });

  it('marks nothing on a scenario kept by hand', () => {
    const said = body(load, '@scenarios/first-miss.scenario.json');
    expect(said).toContain("proves  get-row 'outcome' when status == 404 → noCustomer");
    expect(said.some(line => line.startsWith('generated'))).toBe(false);
    // its answers are inline, so it names no answers file, and its routed lines read them all the same
    expect(said.some(line => line.startsWith('answers'))).toBe(false);
    expect(said).toContain('    op.outcome → noCustomer');
  });
});

describe('wilanis ls scenario: who wrote each', () => {
  it('marks a generated scenario with the command that wrote it, and one kept by hand with nothing', () => {
    const lines = ls(load, 'scenario');
    const line = (path: string) => lines.find(one => one.split(/\s+/)[1] === `@${path}`);
    expect(line(MISSING)).toMatch(/ {2}\(rehearse\)$/);
    expect(line(EMPTY_ID)).toMatch(/ {2}\(edges\)$/);
    expect(line('scenarios/fuzz/get-customer.1.scenario.json')).toMatch(/ {2}\(fuzz\)$/);
    expect(line('scenarios/first-miss.scenario.json')).toMatch(/first-miss\.scenario\.json$/);
  });
});

describe('wilanis describe: a trigger counts the scenarios that replay it', () => {
  it('says after its policies how many were recorded, are edges, were fuzzed and kept by hand, and where they sit', () => {
    const said = body(load, GET_CUSTOMER);
    const at = said.findIndex(line => line.startsWith('scenarios  '));
    expect(said[at - 1]).toMatch(/^ {2}context is what/);
    expect(said.slice(at, at + 5)).toEqual([
      'scenarios  3 recorded, 3 edge(s), 1 fuzzed, 1 by hand',
      '    scenarios/rehearsed/customers.get-customer/',
      '    scenarios/edges/customers.get-customer/',
      '    scenarios/fuzz/',
      '    scenarios/',
    ]);
  });

  it("does not count a policy's decision among the trigger's, since it is the policy's", () => {
    // delete-customer lends its kind to employees-only's and can-register's decisions, recorded under policies/
    expect(body(load, '@features/customers/edge/delete-customer.trigger.json')).toContain(
      'scenarios  3 recorded, 3 edge(s), 0 by hand',
    );
  });

  it('says how to write them where none replays it', () => {
    // a copy leaves the example's own scenarios behind, so nothing replays its triggers
    const bare = copyOfExample();
    try {
      expect(body(loadTree(bare, PLUGINS, INCLUDES), GET_CUSTOMER)).toContain(
        'scenarios  none yet -- wilanis rehearse --record writes one per branch, wilanis fuzz --edges one per input edge',
      );
    } finally {
      rmSync(bare, { recursive: true, force: true });
    }
  });
});
