/**
 * `wilanis fuzz --edges` and its `--check` (RFC 0018): each trigger fired once per fixed edge of its input and the
 * runs written to `scenarios/edges/`, which the command owns, and that directory judged against what the tree writes
 * today, on copies of the example.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { checkTree, walkedUnder } from '@wilanis/compiler';
import { edges, LONG_EDGE, loadTree, type PluginModule, Scope, schemaRef } from '@wilanis/core';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { EDGES, embedderFor, type Fuzzing, fuzz, RECORDED, regress, rehearse } from '../src/index.js';
import { recordedProfile } from '../src/profile.js';
import { copyOfExample, docsDir, INCLUDES, PLUGINS } from './example-harness.js';

const load = (dir: string) => loadTree(dir, PLUGINS, INCLUDES);
const read = (path: string) => JSON.parse(readFileSync(path, 'utf8'));

/** Edit one document of a copied tree in place. */
function edit(dir: string, file: string, change: (doc: any) => void) {
  const doc = read(join(dir, file));
  change(doc);
  writeFileSync(join(dir, file), JSON.stringify(doc, null, 2));
}

/** Every file under a directory with its bytes, by its path inside it. */
function bytesUnder(dir: string): Record<string, string> {
  const files = readdirSync(dir, { recursive: true, encoding: 'utf8' }).filter(file => file.endsWith('.json'));
  return Object.fromEntries(files.sort().map(file => [file, readFileSync(join(dir, file), 'utf8')]));
}

/** The edge files of one trigger of the example, by name inside its directory. */
const filesOf = (answer: Fuzzing, under: string) =>
  (answer.recorded?.written ?? [])
    .filter(file => file.startsWith(`${EDGES}/${under}/`))
    .map(file => file.slice(`${EDGES}/${under}/`.length));

/**
 * How many files the edges directory holds, read off the tree: one per edge of the input of every trigger the default
 * profile serves.
 */
function expectedFiles(dir: string): number {
  const loaded = load(dir);
  const emb = embedderFor(loaded, { seed: 1 });
  const scope = new Scope(loaded.registry, loaded.resolve);
  const profile = recordedProfile(loaded.registry.project?.doc);
  const served = loaded.registry.all('trigger').filter(trigger => walkedUnder(scope, trigger.doc, profile));
  return served.reduce((sum, trigger) => {
    const type = emb.types(trigger.doc).in;
    return sum + (type ? edges(type).length : 0);
  }, 0);
}

describe('fuzz --edges: the edges directory', () => {
  let dir: string;
  let first: Fuzzing;
  beforeAll(async () => {
    dir = copyOfExample();
    first = await fuzz(load(dir), { edges: true });
  }, 60_000);
  afterAll(() => rmSync(dir, { recursive: true, force: true }));

  it("writes one file per trigger and edge of its input, the RFC's rows among them", () => {
    expect(first.ok, first.lines.join('\n')).toBe(true);
    const written = first.recorded?.written ?? [];
    expect(written).toHaveLength(expectedFiles(dir));
    expect(Object.keys(bytesUnder(join(dir, EDGES))).map(file => `${EDGES}/${file}`)).toEqual(written);
    expect(first.written).toEqual(written.map(file => join(dir, file)));
    // a string field: empty, one character, long
    expect(filesOf(first, 'customers.get-customer')).toEqual([
      'id.empty.scenario.json',
      'id.long.scenario.json',
      'id.one.scenario.json',
    ]);
    // two strings and an enum, each member with no cap
    expect(filesOf(first, 'customers.register-customer')).toEqual(
      [
        ...['name', 'email'].flatMap(field => ['empty', 'one', 'long'].map(edge => `${field}.${edge}`)),
        ...['bronze', 'silver', 'gold'].map(member => `tier.enum.${member}`),
      ]
        .map(name => `${name}.scenario.json`)
        .sort(),
    );
    // an optional enum: its members, and left out
    expect(filesOf(first, 'customers.list-customers')).toEqual(
      ['tier.absent', 'tier.enum.bronze', 'tier.enum.gold', 'tier.enum.silver'].map(name => `${name}.scenario.json`),
    );
    // a list: empty, and one generated element
    expect(filesOf(first, 'customers.delete-customers')).toEqual(['ids.empty.scenario.json', 'ids.one.scenario.json']);
    // a blob is not the caller's to choose, so an upload has no edge
    expect(filesOf(first, 'customers.import-customers')).toEqual([]);
    // an included tree's trigger sits under its own feature, apart from any host trigger of its name
    expect(filesOf(first, 'access.refresh').length).toBeGreaterThan(0);
  });

  it("writes each run as the seed's run with the one field set, marked generated by edges", () => {
    const seed = read(join(dir, EDGES, 'customers.get-customer/id.one.scenario.json'));
    const long = read(join(dir, EDGES, 'customers.get-customer/id.long.scenario.json'));
    expect(long).toMatchObject({
      description: `get-customer under seed 1 with id long: ${long.expect.status}. Written by wilanis fuzz --edges; regenerate it, do not edit it.`,
      generated: 'edges',
      trigger: '@features/customers/edge/get-customer.trigger.json',
      seed: 1,
      in: { id: 'x'.repeat(LONG_EDGE) },
    });
    // the context is the seed's whatever the edge, since the input is what the edge varies
    expect(long.context).toEqual(seed.context);
    const absent = read(join(dir, EDGES, 'customers.list-customers/tier.absent.scenario.json'));
    expect(absent.in).toEqual({});
    expect(read(join(dir, EDGES, 'customers.list-customers/tier.enum.gold.scenario.json')).in).toEqual({
      tier: 'gold',
    });
    for (const file of Object.keys(bytesUnder(join(dir, EDGES))))
      expect(read(join(dir, EDGES, file)).generated).toBe('edges');
  });

  it('is deterministic: byte-identical a second time, and check finds it current', async () => {
    const before = bytesUnder(join(dir, EDGES));
    const again = await fuzz(load(dir), { edges: true });
    expect(again.recorded?.written).toEqual(first.recorded?.written);
    expect(bytesUnder(join(dir, EDGES))).toEqual(before);
    const checked = await fuzz(load(dir), { edges: true, check: true });
    expect(checked.recorded?.check).toEqual({ stale: [], missing: [], extra: [] });
    expect(checked.written).toEqual([]);
  }, 60_000);

  it('is a suite that passes: it loads, check refuses nothing, and regress replays every file the same', async () => {
    const loaded = load(dir);
    expect(loaded.registry.all('scenario')).toHaveLength(first.recorded?.files ?? -1);
    expect(checkTree(loaded).items).toEqual([]);
    const replayed = await regress(loaded);
    expect(replayed.ok, replayed.lines.filter(line => !line.endsWith(': same')).join('\n')).toBe(true);
    expect(replayed.results).toHaveLength(first.recorded?.files ?? -1);
  });
});

describe('fuzz --edges --check: an edges directory the tree has moved away from', () => {
  it('lists a file edited by hand stale, one removed missing and an orphan of its own extra', {
    timeout: 60_000,
  }, async () => {
    const dir = copyOfExample();
    await fuzz(load(dir), { edges: true });
    const edited = `${EDGES}/customers.get-customer/id.empty.scenario.json`;
    const doc = read(join(dir, edited));
    writeFileSync(join(dir, edited), JSON.stringify({ ...doc, expect: { ...doc.expect, status: 'done' } }, null, 2));
    const removed = `${EDGES}/customers.get-customer/id.one.scenario.json`;
    rmSync(join(dir, removed));
    // what an earlier fuzz --edges wrote of a field the input no longer has
    const orphan = `${EDGES}/customers.get-customer/gone.empty.scenario.json`;
    writeFileSync(join(dir, orphan), JSON.stringify(doc, null, 2));
    const checked = await fuzz(load(dir), { edges: true, check: true });
    expect(checked.recorded?.check).toEqual({ stale: [edited], missing: [removed], extra: [orphan] });
    // nothing was written: the check only reads
    expect(existsSync(join(dir, removed))).toBe(false);
    const rewritten = await fuzz(load(dir), { edges: true });
    expect(rewritten.recorded?.written).toContain(removed);
    expect(existsSync(join(dir, orphan))).toBe(false);
    expect((await fuzz(load(dir), { edges: true, check: true })).recorded?.check).toEqual({
      stale: [],
      missing: [],
      extra: [],
    });
    rmSync(dir, { recursive: true, force: true });
  });

  it('answers new optional fields as the files they add, missing until written', { timeout: 60_000 }, async () => {
    const dir = copyOfExample();
    await fuzz(load(dir), { edges: true });
    const shape = join(dir, 'features/customers/edge/IdRequest.shape.json');
    const doc = read(shape);
    doc.fields.verbose = { type: 'boolean', required: false, description: 'Whether to say more.' };
    // an object the seed's input leaves out: an edge inside it is set in one generated whole
    const where = { fields: { name: { type: 'string' }, limit: { type: 'number' } } };
    doc.fields.where = { type: where, required: false, description: 'What to narrow the answer to.' };
    writeFileSync(shape, JSON.stringify(doc, null, 2));
    // the operations behind IdRequest take an id and no more, so the four triggers handing it them are T002 since
    // #787; what fuzz --edges writes is read off the trigger's in all the same
    expect(checkTree(load(dir)).items.map(one => `${one.code} ${one.file}`)).toEqual(
      ['delete-customer', 'enqueue-removal', 'get-customer', 'remove-queued'].map(
        name => `T002 @features/customers/edge/${name}.trigger.json`,
      ),
    );
    const checked = await fuzz(load(dir), { edges: true, check: true });
    const added = checked.recorded?.check?.missing ?? [];
    const under = `${EDGES}/customers.get-customer`;
    for (const edge of ['verbose.true', 'verbose.false', 'verbose.absent', 'where.name.empty', 'where.absent'])
      expect(added).toContain(`${under}/${edge}.scenario.json`);
    await fuzz(load(dir), { edges: true });
    const inside = read(join(dir, under, 'where.name.empty.scenario.json'));
    expect(inside.in).toEqual({ id: expect.any(String), where: { name: '', limit: expect.any(Number) } });
    expect(read(join(dir, under, 'where.limit.negative.scenario.json')).in.where).toMatchObject({ limit: -1 });
    rmSync(dir, { recursive: true, force: true });
  });
});

describe('fuzz --edges: what the edges directory owns', () => {
  it('owns what it wrote: a scenario a person or another command wrote there is kept, and one in the way refused', {
    timeout: 60_000,
  }, async () => {
    const dir = copyOfExample();
    const answer = await fuzz(load(dir), { edges: true });
    const one = read(join(dir, EDGES, 'customers.get-customer/id.one.scenario.json'));
    const { generated: _, ...kept } = one;
    const mine = JSON.stringify({ ...kept, description: 'an id of one character, kept by hand' }, null, 2);
    const byHand = `${EDGES}/mine.scenario.json`;
    writeFileSync(join(dir, byHand), mine);
    // one the rehearsal wrote is not fuzz's either
    const rehearsed = `${EDGES}/rehearsed.scenario.json`;
    writeFileSync(join(dir, rehearsed), JSON.stringify({ ...one, generated: 'rehearse' }, null, 2));
    const again = await fuzz(load(dir), { edges: true });
    expect(again.recorded?.written).toEqual(answer.recorded?.written);
    expect(readFileSync(join(dir, byHand), 'utf8')).toBe(mine);
    expect(again.recorded?.kept).toEqual([byHand, rehearsed]);
    const checked = await fuzz(load(dir), { edges: true, check: true });
    expect(checked.recorded?.check).toEqual({ stale: [], missing: [], extra: [] });
    // one in the way of a file it writes refuses the write, and nothing is written or removed
    const inTheWay = `${EDGES}/customers.get-customer/id.one.scenario.json`;
    writeFileSync(join(dir, inTheWay), mine);
    await expect(fuzz(load(dir), { edges: true })).rejects.toThrow(
      `${inTheWay} would be written over, and fuzz --edges did not write it (no "generated": "edges"): ` +
        `move it out of ${EDGES}/, where fuzz --edges writes`,
    );
    expect(readFileSync(join(dir, inTheWay), 'utf8')).toBe(mine);
    rmSync(dir, { recursive: true, force: true });
  });

  it('is scenarios/edges/ in the tree and nowhere else, and --record may not own it', { timeout: 60_000 }, async () => {
    const dir = copyOfExample();
    const elsewhere = join(tmpdir(), `wilanis-edges-${process.pid}`);
    mkdirSync(elsewhere, { recursive: true });
    writeFileSync(join(elsewhere, 'keep.scenario.json'), '{"generated":"edges"}');
    mkdirSync(join(dir, 'scenarios'), { recursive: true });
    symlinkSync(elsewhere, join(dir, EDGES));
    await expect(fuzz(load(dir), { edges: true })).rejects.toThrow(`${EDGES} leads through a link to `);
    expect(readdirSync(elsewhere)).toEqual(['keep.scenario.json']);
    rmSync(join(dir, EDGES));
    rmSync(elsewhere, { recursive: true, force: true });
    const where = `it may be any directory below scenarios/ outside scenarios/fuzz/ and ${EDGES}/, as ${RECORDED}/ is`;
    for (const at of [EDGES, `${EDGES}/customers`, 'scenarios/EDGES'])
      await expect(rehearse(load(dir), { record: at })).rejects.toThrow(where);
    rmSync(dir, { recursive: true, force: true });
  });

  it('refuses two triggers of one feature and one name, which would share a directory', {
    timeout: 60_000,
  }, async () => {
    const dir = copyOfExample();
    await fuzz(load(dir), { edges: true });
    // a second get-customer under the same feature's edge/v2/ would share customers.get-customer/: refused, naming
    // the two files, rather than one's runs written over the other's
    const trigger = read(join(dir, 'features/customers/edge/get-customer.trigger.json'));
    mkdirSync(join(dir, 'features/customers/edge/v2'));
    writeFileSync(
      join(dir, 'features/customers/edge/v2/get-customer.trigger.json'),
      JSON.stringify({ ...trigger, settings: { ...trigger.settings, route: '/v2/customers/{id}' } }),
    );
    expect(checkTree(load(dir)).items).toEqual([]);
    const before = bytesUnder(join(dir, EDGES));
    // the refusal rehearse --record makes, word for word, since the directory is the same rule's
    const refusal =
      "two triggers of feature 'customers' are named 'get-customer', and a recorded trigger's scenarios are written " +
      'under its feature and name (customers.get-customer/): rename ' +
      '@features/customers/edge/get-customer.trigger.json or @features/customers/edge/v2/get-customer.trigger.json';
    await expect(fuzz(load(dir), { edges: true })).rejects.toThrow(refusal);
    await expect(rehearse(load(dir), { record: RECORDED })).rejects.toThrow(refusal);
    expect(bytesUnder(join(dir, EDGES))).toEqual(before);
    rmSync(dir, { recursive: true, force: true });
  });

  it('names the directory of a trigger outside a feature as rehearse --record does', { timeout: 60_000 }, async () => {
    const dir = copyOfExample();
    // a tree's own trigger outside a feature is refused as D008 before it is registered, so the one trigger in no
    // feature is one a plugin ships: read off its path as the recorded runs are, its directory is the plugin's root
    // before its name, never `undefined`
    const trigger = read(join(dir, 'features/customers/edge/get-customer.trigger.json'));
    const loose: PluginModule = {
      root: '@loose',
      docs: docsDir({
        'plugin.json': { $schema: schemaRef('plugin'), description: 'a plugin that ships a trigger' },
        'get-customer.trigger.json': { ...trigger, settings: { ...trigger.settings, route: '/loose/customers/{id}' } },
      }),
      handlers: {},
    };
    edit(dir, 'project.json', doc => doc.plugins.push({ use: '@loose' }));
    const loaded = loadTree(dir, { ...PLUGINS, '@loose': loose }, INCLUDES);
    const shipped = loaded.registry.all('trigger').find(one => one.path === '@loose/get-customer.trigger.json');
    expect(shipped?.name).toBe('get-customer');
    expect(shipped?.feature).toBeUndefined();
    const edged = await fuzz(loaded, { edges: true });
    const recorded = await rehearse(loaded, { record: RECORDED });
    const dirsOf = (written: string[] | undefined, under: string) => [
      ...new Set((written ?? []).map(file => file.slice(under.length + 1).split('/')[0])),
    ];
    expect(dirsOf(edged.recorded?.written, EDGES)).toContain('loose.get-customer');
    expect(dirsOf(recorded.recorded?.written, RECORDED)).toContain('loose.get-customer');
    expect(dirsOf(edged.recorded?.written, EDGES).filter(one => one.startsWith('undefined'))).toEqual([]);
    rmSync(dir, { recursive: true, force: true });
    rmSync(loose.docs, { recursive: true, force: true });
  });

  it('refuses what would make the directory depend on more than the tree', async () => {
    const loaded = load(copyOfExample());
    await expect(fuzz(loaded, { check: true })).rejects.toThrow(
      'check says whether scenarios/edges/ is what fuzz --edges writes: fuzz --edges --check',
    );
    await expect(fuzz(loaded, { edges: true, runs: 2 })).rejects.toThrow('drop --runs');
    await expect(fuzz(loaded, { edges: true, profile: 'live' })).rejects.toThrow('drop --profile');
    await expect(fuzz(loaded, { edges: true, out: 'scenarios/mine' })).rejects.toThrow('drop --out');
    rmSync(loaded.root, { recursive: true, force: true });
  });
});
