/**
 * RFC 0018, step 2: a scenario records the refusal its run declared (`expect.reason`, read by `refusalOf`, which no
 * node's `out` carries) and `regress` compares it, so a refuse node whose reason changes is a diff of the run and not
 * only of a node; and plain `fuzz` owns `scenarios/fuzz/`, marking what it writes `generated: "fuzz"`. The example's
 * GET /customers/{id} under seed 1 routes to `upstreamFailed`, which refuses `upstream`.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { checkTree } from '@wilanis/compiler';
import { loadTree } from '@wilanis/core';
import { describe, expect, it } from 'vitest';
import { fuzz, regress } from '../src/index.js';
import { copyOfExample, INCLUDES, PLUGINS } from './example-harness.js';

const GRAPH = 'features/customers/data/get-row.graph.json';
const FUZZED = 'scenarios/fuzz/get-customer.1.scenario.json';
const read = (path: string) => JSON.parse(readFileSync(path, 'utf8'));
const load = (dir: string) => loadTree(dir, PLUGINS, INCLUDES);

/** Change the reason the seed-1 run of get-customer refuses with, in a copy of the example. */
function editRefusal(dir: string, reason: string): void {
  const file = join(dir, GRAPH);
  const doc = read(file);
  doc.nodes.find((node: { id: string }) => node.id === 'upstreamFailed').in.reason = reason;
  writeFileSync(file, JSON.stringify(doc));
}

/** A copy of the example fuzzed once per trigger; the caller removes it. */
async function fuzzedCopy(): Promise<{ dir: string; written: string[] }> {
  const dir = copyOfExample();
  const fuzzed = await fuzz(load(dir), { runs: 1, profile: 'live' });
  expect(fuzzed.ok, fuzzed.lines.join('\n')).toBe(true);
  return { dir, written: fuzzed.written };
}

/** What regress says of the scenario at `path`, under the root. */
async function lineOf(dir: string, path: string): Promise<string | undefined> {
  const answer = await regress(load(dir), { profile: 'live' });
  return answer.lines.find(line => line.startsWith(`@${path}:`));
}

describe('fuzz owns scenarios/fuzz and marks what it writes', () => {
  it('writes <trigger>.<seed>.scenario.json under scenarios/fuzz/, each generated by fuzz, nothing flat', async () => {
    const { dir, written } = await fuzzedCopy();
    expect(written.length).toBeGreaterThan(0);
    for (const file of written) {
      expect(file.startsWith(join(dir, 'scenarios', 'fuzz'))).toBe(true);
      expect(read(file).generated).toBe('fuzz');
    }
    // scenarios/ itself holds only the directory fuzz owns: what a person keeps there is theirs
    expect(readdirSync(join(dir, 'scenarios'))).toEqual(['fuzz']);
    const { description } = read(join(dir, FUZZED));
    expect(description).toContain('regenerate it, do not edit it');
    // a pinned copy says why it is kept, so it never reads as a leftover of an older fuzz
    expect(description).toContain('give it a description of its own, and drop generated');
    rmSync(dir, { recursive: true, force: true });
  });

  it('keeps --out as it was: the directory named, under the root', async () => {
    const dir = copyOfExample();
    const { written } = await fuzz(load(dir), { runs: 1, profile: 'live', out: 'elsewhere' });
    expect(written.every(file => file.startsWith(join(dir, 'elsewhere')))).toBe(true);
    expect(existsSync(join(dir, 'scenarios', 'fuzz'))).toBe(false);
    rmSync(dir, { recursive: true, force: true });
  });
});

describe('a scenario records the refusal its run declared, and regress compares it', () => {
  it('records the reason of a run that refused, and none on a run that answered', async () => {
    const { dir, written } = await fuzzedCopy();
    const refused = read(join(dir, FUZZED)).expect;
    expect(refused).toMatchObject({ status: 'failed', reason: 'upstream' });
    for (const file of written) {
      const { expect: recorded } = read(file);
      if (recorded.status !== 'failed') expect(recorded.reason, file).toBeUndefined();
    }
    // the field passes check and replays as the same
    expect(checkTree(load(dir)).items).toEqual([]);
    expect(await lineOf(dir, FUZZED)).toBe(`@${FUZZED}: same`);
    rmSync(dir, { recursive: true, force: true });
  });

  it('a declared reason that changed is a diff of the run, said after the nodes that moved with it', async () => {
    const { dir } = await fuzzedCopy();
    editRefusal(dir, 'gone');
    const line = await lineOf(dir, FUZZED);
    expect(line).toMatch(/^.+: DIFF .+; reason upstream → gone$/);
    expect(line).toContain('op.upstreamFailed: reason upstream → gone');
    rmSync(dir, { recursive: true, force: true });
  });

  it('a declared refusal become a fault reads as a reason of none', async () => {
    const { dir } = await fuzzedCopy();
    // a reason that is not a word: the refuse handler breaks instead of refusing
    editRefusal(dir, '{{fetched.status}}');
    expect(await lineOf(dir, FUZZED)).toMatch(/; reason upstream → none$/);
    rmSync(dir, { recursive: true, force: true });
  });

  it('a hand-written scenario that pins the reason is held to it; one that does not is not', async () => {
    const { dir } = await fuzzedCopy();
    const recorded = read(join(dir, FUZZED));
    const { generated: _, ...byHand } = recorded;
    for (const node of Object.values(byHand.expect.nodes) as { reason?: string }[]) delete node.reason;
    mkdirSync(join(dir, 'scenarios'), { recursive: true });
    writeFileSync(join(dir, 'scenarios/pinned.scenario.json'), JSON.stringify(byHand));
    const { reason: __, ...unpinned } = byHand.expect;
    writeFileSync(join(dir, 'scenarios/unpinned.scenario.json'), JSON.stringify({ ...byHand, expect: unpinned }));
    expect(checkTree(load(dir)).items).toEqual([]);
    editRefusal(dir, 'gone');
    expect(await lineOf(dir, 'scenarios/pinned.scenario.json')).toBe(
      '@scenarios/pinned.scenario.json: DIFF reason upstream → gone',
    );
    expect(await lineOf(dir, 'scenarios/unpinned.scenario.json')).toBe('@scenarios/unpinned.scenario.json: same');
    rmSync(dir, { recursive: true, force: true });
  });

  it('a scenario a command wrote is held to the reason it recorded, none included', async () => {
    const { dir } = await fuzzedCopy();
    const recorded = read(join(dir, FUZZED));
    const { reason: _, ...unrecorded } = recorded.expect;
    writeFileSync(join(dir, FUZZED), JSON.stringify({ ...recorded, expect: unrecorded }));
    expect(await lineOf(dir, FUZZED)).toBe(`@${FUZZED}: DIFF reason none → upstream`);
    rmSync(dir, { recursive: true, force: true });
  });
});
