/**
 * The files a target renders, on disk (RFC 0024). Every one carries the two-line header that says it is generated,
 * from which tree and profiles, and the command that renders it again. A file whose first line is not a generated
 * header is someone's own -- a Dockerfile a tree outgrew and took over -- and is overwritten only with `--force`.
 * `--check` writes nothing and says what a write would change. A renderer answers `{ path, contents }` from a plan
 * and never touches the disk; this module is the one that does, and it judges every file before it writes any, so a
 * refusal leaves the directory as it was.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

/** One file a target renders: its path under the directory it is written into, and its whole text. */
export interface Rendered {
  path: string;
  contents: string;
}

/** Where a file came from, as its header says: the root as the command was given it, the profiles, the flags beyond. */
export interface Origin {
  root: string;
  profiles: string[];
  flags: string[];
}

/** What a write is asked to do beside writing: only say what would change, and overwrite a file it did not write. */
export interface WriteOptions {
  check: boolean;
  force: boolean;
}

/**
 * What a write did or would do: whether the directory is, or now is, as the targets render it; the lines that say
 * so; and whether it was refused, a file someone owns standing where one would go, so that nothing was written.
 */
export interface Written {
  ok: boolean;
  said: string[];
  refused: boolean;
}

/** How every generated file's first line begins: how a file this command wrote is told from one it did not. */
export const GENERATED = '# generated by wilanis-deploy';

/** One word of a command line as a shell reads it back: as it is where nothing in it is special, else single-quoted. */
export const shellWord = (word: string): string =>
  /^[\w@%+=:,./-]+$/.test(word) ? word : `'${word.replaceAll("'", `'\\''`)}'`;

/** The command that renders a file again: the root, each profile, and the flags that chose where and what. */
export function regenerateOf(origin: Origin): string {
  const profiles = origin.profiles.flatMap(profile => ['--profile', profile]);
  return ['npx', 'wilanis-deploy', origin.root, ...profiles, ...origin.flags].map(shellWord).join(' ');
}

/** The profiles a header names: one, several, or the unnamed one of a tree that declares none. */
function profilesSaid(profiles: string[]): string {
  const [only] = profiles;
  if (profiles.length === 1 && only !== undefined) return only === '' ? 'the unnamed profile' : `profile ${only}`;
  return `profiles ${profiles.map(profile => (profile === '' ? "''" : profile)).join(', ')}`;
}

/** The two lines every generated file begins with: that it is generated and from what, and how to render it again. */
export const headerOf = (origin: Origin): string =>
  `${GENERATED} from ${origin.root} (${profilesSaid(origin.profiles)}) -- do not edit\n` +
  `# regenerate: ${regenerateOf(origin)}\n`;

/** A rendered file with its header above it, as it is written. */
export const stamped = (file: Rendered, origin: Origin): Rendered => ({
  path: file.path,
  contents: headerOf(origin) + file.contents,
});

/** What writing one file would do to what is on disk: write it anew, change it, leave it, or meet someone's own. */
type Fate =
  | { state: 'new' }
  | { state: 'same' }
  | { state: 'changed'; line: number; was: string; now: string }
  | { state: 'foreign' };

/** One file to write, where it goes, as a message names it, and what writing it would do. */
interface Judged {
  file: Rendered;
  shown: string;
  fate: Fate;
}

/** The first line two texts differ at, counted from 1, with what each holds there. */
function firstChange(was: string, now: string): Fate {
  const before = was.split('\n');
  const after = now.split('\n');
  const at = after.findIndex((line, index) => line !== before[index]);
  const line = at < 0 ? after.length : at;
  const said = (lines: string[]) => lines[line]?.trim() ?? '(end of file)';
  return { state: 'changed', line: line + 1, was: said(before), now: said(after) };
}

/** What writing a file over what is at its path would do. */
function fateOf(path: string, contents: string): Fate {
  if (!existsSync(path)) return { state: 'new' };
  const on = readFileSync(path, 'utf8');
  if (on === contents) return { state: 'same' };
  if (!on.startsWith(GENERATED)) return { state: 'foreign' };
  return firstChange(on, contents);
}

/** The refusal a file someone owns meets, naming both ways past it. */
const foreignSaid = (shown: string): string =>
  `${shown} is not one wilanis-deploy wrote: its first line is not the generated header, so it is left as it is\n` +
  '→ to keep it, render only the other targets with --target; to replace it with the generated one, pass --force';

/** What `--check` says of one file a write would touch; nothing for a file already as the target renders it. */
function wouldSaid({ shown, fate }: Judged): string[] {
  if (fate.state === 'new') return [`${shown} would be written`];
  if (fate.state === 'foreign') return [`${shown} would be overwritten, though wilanis-deploy did not write it`];
  if (fate.state === 'changed') return [`${shown} would change at line ${fate.line}: ${fate.was} → ${fate.now}`];
  return [];
}

/** Every file written where it differs from what is on disk, with a line each saying which were written. */
function written(dir: string, judged: Judged[]): Written {
  for (const { file, fate } of judged) {
    if (fate.state === 'same') continue;
    const path = join(dir, file.path);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, file.contents);
  }
  const said = judged.map(({ shown, fate }) => `${fate.state === 'same' ? 'unchanged' : 'wrote'} ${shown}`);
  return { ok: true, said, refused: false };
}

/**
 * The files written into a directory, or with `check` only judged: every file is judged first, and where one is
 * someone's own and `force` was not given, nothing is written and the refusal names `--force`. `check` answers
 * `ok` only where a write would change nothing.
 */
export function writeInto(dir: string, files: Rendered[], options: WriteOptions): Written {
  const judged = files.map(file => ({
    file,
    shown: join(dir, file.path),
    fate: fateOf(join(dir, file.path), file.contents),
  }));
  const refused = options.force ? [] : judged.filter(one => one.fate.state === 'foreign');
  if (refused.length) return { ok: false, said: refused.map(one => foreignSaid(one.shown)), refused: true };
  if (!options.check) return written(dir, judged);
  const said = judged.flatMap(wouldSaid);
  return { ok: !said.length, said, refused: false };
}
