/**
 * `wilanis fuzz` and `wilanis regress`: many runs of a trigger against stubbed effects, each written out as a scenario,
 * and those scenarios replayed to say whether the tree still answers as it did.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { LoadResult } from '@wilanis/core';
import { HOME, type ScenarioDoc, schemaUrl } from '@wilanis/core';
import type { Report } from '@wilanis/engine';
import { embedderFor, generatedFire } from './stubbing.js';

// ---- fuzz / regress ----------------------------------------------------------------------------------

/** Where fuzz writes, under the root: the one directory placement says a scenario lives in (HOME, D008). */
export const SCENARIOS = HOME.scenario?.dir ?? 'scenarios';

/**
 * What one node did: how it ended, the operation it ran, where a switch routed, and what it answered. The
 * handler is kept beside the rest because a node whose binding was changed under it answers differently for
 * a reason no diff of the answer alone can name.
 *
 * Durations are deliberately absent: they are not reproducible, so a scenario would diff against itself.
 */
function did(node: Report['nodes'][string]): ScenarioDoc['expect']['nodes'][string] {
  return {
    status: node.status,
    ...(node.handler ? { handler: node.handler } : {}),
    ...(node.selected ? { selected: node.selected } : {}),
    ...(node.status === 'done' && node.out !== undefined ? { out: node.out } : {}),
  };
}

/** What every node of a run did, by its dotted path, a nested graph's nodes under the node that called it. */
function pick(report: Report, prefix = ''): ScenarioDoc['expect']['nodes'] {
  const out: ScenarioDoc['expect']['nodes'] = {};
  for (const [id, node] of Object.entries(report.nodes)) {
    const key = prefix ? `${prefix}.${id}` : id;
    out[key] = did(node);
    if (node.sub) Object.assign(out, pick(node.sub, key));
  }
  return out;
}

/** Run each trigger under N seeds with stubbed effects and write one scenario per run. */
export async function fuzz(
  load: LoadResult,
  opts: { runs?: number; profile?: string; out?: string } = {},
): Promise<string[]> {
  const written: string[] = [];
  const dir = join(load.root, opts.out ?? SCENARIOS);
  mkdirSync(dir, { recursive: true });
  for (const trigger of load.registry.all('trigger')) {
    for (let seed = 1; seed <= (opts.runs ?? 5); seed++) {
      const record: Record<string, unknown> = {};
      const emb = embedderFor(load, { seed, record, profile: opts.profile });
      const { input, request } = generatedFire(emb, trigger, seed);
      const report = await emb.fire(trigger.doc, input, request);
      const sc: ScenarioDoc = {
        $schema: schemaUrl('scenario'),
        description: `${trigger.path} under seed ${seed}: ${report.status}. Generated by wilanis fuzz; edit stubs to pin an edge case.`,
        trigger: trigger.path,
        seed,
        in: input,
        request,
        stubs: record,
        expect: {
          status: report.status,
          ...(report.status === 'done' ? { output: report.output } : {}),
          nodes: pick(report),
        },
      };
      const file = join(dir, `${trigger.name}.${seed}.scenario.json`);
      writeFileSync(file, `${JSON.stringify(sc, null, 2)}\n`);
      written.push(file);
    }
  }
  return written;
}

const same = (one: unknown, other: unknown) => JSON.stringify(one) === JSON.stringify(other);

/** How one node differs from what the scenario recorded. */
function nodeDiffs(
  id: string,
  was: ScenarioDoc['expect']['nodes'][string],
  now: ScenarioDoc['expect']['nodes'][string] | undefined,
): string[] {
  if (!now) return [`${id}: gone`];
  const out: string[] = [];
  if (now.status !== was.status) out.push(`${id}: ${was.status} → ${now.status}`);
  if (was.handler && now.handler !== was.handler) out.push(`${id}: ran ${was.handler} → ${now.handler}`);
  if (was.selected && now.selected !== was.selected) out.push(`${id}: routed ${was.selected} → ${now.selected}`);
  if ('out' in was && !same(now.out, was.out)) out.push(`${id}: out changed`);
  return out;
}

/** How this run differs from what the scenario recorded: its status, its output, and every node. */
function diffOf(report: Report, expect: ScenarioDoc['expect']): string[] {
  const diffs: string[] = [];
  if (report.status !== expect.status) diffs.push(`status ${expect.status} → ${report.status}`);
  if (expect.status === 'done' && !same(report.output, expect.output)) diffs.push('output changed');
  const got = pick(report);
  for (const [id, was] of Object.entries(expect.nodes)) diffs.push(...nodeDiffs(id, was, got[id]));
  for (const id of Object.keys(got)) if (!(id in expect.nodes)) diffs.push(`${id}: new`);
  return diffs;
}

/** Replay every scenario with its recorded stubs and diff the report node by node. */
export async function regress(
  load: LoadResult,
  opts: { profile?: string } = {},
): Promise<{ ok: boolean; lines: string[] }> {
  const lines: string[] = [];
  let ok = true;
  const emb = embedderFor(load, { seed: 0, profile: opts.profile, env: fakeEnvFor(load) });
  for (const sc of load.registry.all('scenario')) {
    const trigger = load.registry.all('trigger').find(trigger => trigger.path === load.resolve(sc.doc.trigger));
    // S001 has already refused a scenario whose trigger is gone; skip rather than replay nothing.
    if (!trigger) {
      ok = false;
      lines.push(`${sc.path}: names unknown trigger '${sc.doc.trigger}'`);
      continue;
    }
    const report: Report = await emb.fire(trigger.doc, sc.doc.in, sc.doc.request ?? {}, { stubs: sc.doc.stubs });
    const diffs = diffOf(report, sc.doc.expect);
    if (diffs.length) ok = false;
    lines.push(`${sc.path}: ${diffs.length ? `DIFF ${diffs.join('; ')}` : 'same'}`);
  }
  return { ok, lines };
}

function fakeEnvFor(load: LoadResult): NodeJS.ProcessEnv {
  const env: NodeJS.ProcessEnv = {};
  for (const name of Object.values(load.registry.project?.doc.secrets ?? {})) env[name] = `stub-${name.toLowerCase()}`;
  return env;
}
