/**
 * `wilanis fuzz` and `wilanis regress`: many runs of a trigger against stubbed effects, each written out as a scenario,
 * and those scenarios replayed to say whether the tree still answers as it did.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Loaded, LoadResult } from '@wilanis/core';
import { HOME, type ScenarioDoc, schemaUrl, type TriggerDoc } from '@wilanis/core';
import { outcomeOf, type Report } from '@wilanis/engine';
import { activeProfile } from './profile.js';
import { embedderFor, generatedFire } from './stubbing.js';

// ---- fuzz / regress ----------------------------------------------------------------------------------

/** Where fuzz writes, under the root: the one directory placement says a scenario lives in (HOME, D008). */
export const SCENARIOS = HOME.scenario?.dir ?? 'scenarios';

/**
 * What one node did: how it ended, the reason it refused with, the operation it ran, where a switch routed, and
 * what it answered. The handler is kept beside the rest because a node whose binding was changed under it answers
 * differently for a reason no diff of the answer alone can name; the reason, because a refusal and a fault at the
 * same node are both `failed`.
 *
 * Durations are deliberately absent: they are not reproducible, so a scenario would diff against itself.
 */
function did(node: Report['nodes'][string]): ScenarioDoc['expect']['nodes'][string] {
  return {
    status: node.status,
    ...(node.status === 'failed' && node.reason !== undefined ? { reason: node.reason } : {}),
    ...(node.handler ? { handler: node.handler } : {}),
    ...(node.selected ? { selected: node.selected } : {}),
    ...(node.status === 'done' && node.out !== undefined ? { out: node.out } : {}),
  };
}

/** What every node of a run did, by its dotted path, a nested graph's nodes under the node that called it. */
function pick(report: Report, prefix = ''): ScenarioDoc['expect']['nodes'] {
  const out: ScenarioDoc['expect']['nodes'] = {};
  for (const [id, node] of Object.entries(report.nodes)) {
    const key = prefix ? `${prefix}.${id}` : id;
    out[key] = did(node);
    if (node.sub) Object.assign(out, pick(node.sub, key));
  }
  return out;
}

/** One fuzzed run: the trigger fired under a seed, what it was fired with, what the stubs answered, its report. */
interface Fuzzed {
  trigger: Loaded<TriggerDoc>;
  seed: number;
  input: unknown;
  request: Record<string, unknown>;
  record: Record<string, unknown>;
  report: Report;
}

/** Fire one trigger under one seed with stubbed effects, recording every stub's answer. */
async function fuzzed(load: LoadResult, trigger: Loaded<TriggerDoc>, seed: number, profile?: string): Promise<Fuzzed> {
  const record: Record<string, unknown> = {};
  const emb = embedderFor(load, { seed, record, profile });
  const { input, request } = generatedFire(emb, trigger, seed);
  const report = await emb.fire(trigger.doc, input, request);
  return { trigger, seed, input, request, record, report };
}

/** The scenario a fuzzed run is written as. */
function scenarioOf({ trigger, seed, input, request, record, report }: Fuzzed): ScenarioDoc {
  return {
    $schema: schemaUrl('scenario'),
    description: `${trigger.path} under seed ${seed}: ${report.status}. Generated by wilanis fuzz; edit stubs to pin an edge case.`,
    trigger: trigger.path,
    seed,
    in: input,
    request,
    stubs: record,
    expect: {
      status: report.status,
      ...(report.status === 'done' ? { output: report.output } : {}),
      nodes: pick(report),
    },
  };
}

/**
 * Run each trigger under N seeds with stubbed effects and write one scenario per run -- but never one of a fault.
 * The stubbed world never throws, so a run that faults under stubs is the tree's own bug (a `make` whose value does
 * not fit, a `refuse` whose reason is not a word, a wiring hole), and a scenario pinning it would hold the tree to
 * breaking: the fault is said, nothing is written for it, and the answer is not ok.
 */
export async function fuzz(
  load: LoadResult,
  opts: { runs?: number; profile?: string; out?: string } = {},
): Promise<{ ok: boolean; written: string[]; lines: string[] }> {
  const written: string[] = [];
  const lines: string[] = [];
  const profile = activeProfile(load.registry.project?.doc, { flag: opts.profile, env: process.env });
  const dir = join(load.root, opts.out ?? SCENARIOS);
  mkdirSync(dir, { recursive: true });
  for (const trigger of load.registry.all('trigger')) {
    for (let seed = 1; seed <= (opts.runs ?? 5); seed++) {
      const run = await fuzzed(load, trigger, seed, profile);
      const outcome = outcomeOf(run.report);
      if (outcome.kind === 'faulted') {
        lines.push(`${trigger.path} under seed ${seed}: FAULT at '${outcome.at}': ${outcome.error}`);
        continue;
      }
      const file = join(dir, `${trigger.name}.${seed}.scenario.json`);
      writeFileSync(file, `${JSON.stringify(scenarioOf(run), null, 2)}\n`);
      written.push(file);
    }
  }
  return { ok: lines.length === 0, written, lines };
}

const same = (one: unknown, other: unknown) => JSON.stringify(one) === JSON.stringify(other);

/** How a node's reason differs: `none` for a node that answered or broke, so a refusal become a fault reads as one. */
function reasonDiffs(id: string, was: string | undefined, now: string | undefined): string[] {
  return now === was ? [] : [`${id}: reason ${was ?? 'none'} → ${now ?? 'none'}`];
}

/**
 * How one node differs from what the scenario recorded. A reason is diffed only where the scenario pins reasons at
 * all: one written before fuzz recorded them has none on any node, and replays as it did.
 */
function nodeDiffs(
  id: string,
  was: ScenarioDoc['expect']['nodes'][string],
  now: ScenarioDoc['expect']['nodes'][string] | undefined,
  pinsReasons: boolean,
): string[] {
  if (!now) return [`${id}: gone`];
  const out: string[] = [];
  if (now.status !== was.status) out.push(`${id}: ${was.status} → ${now.status}`);
  if (pinsReasons) out.push(...reasonDiffs(id, was.reason, now.reason));
  if (was.handler && now.handler !== was.handler) out.push(`${id}: ran ${was.handler} → ${now.handler}`);
  if (was.selected && now.selected !== was.selected) out.push(`${id}: routed ${was.selected} → ${now.selected}`);
  if ('out' in was && !same(now.out, was.out)) out.push(`${id}: out changed`);
  return out;
}

/** How this run differs from what the scenario recorded: its status, its output, and every node. */
function diffOf(report: Report, expect: ScenarioDoc['expect']): string[] {
  const diffs: string[] = [];
  if (report.status !== expect.status) diffs.push(`status ${expect.status} → ${report.status}`);
  if (expect.status === 'done' && !same(report.output, expect.output)) diffs.push('output changed');
  const got = pick(report);
  const pinsReasons = Object.values(expect.nodes).some(node => node.reason !== undefined);
  for (const [id, was] of Object.entries(expect.nodes)) diffs.push(...nodeDiffs(id, was, got[id], pinsReasons));
  for (const id of Object.keys(got)) if (!(id in expect.nodes)) diffs.push(`${id}: new`);
  return diffs;
}

/** One scenario replayed: whether the run matched what it recorded, and each difference said in words. */
export interface Replayed {
  scenario: string;
  same: boolean;
  diffs: string[];
}

/** What `regress` answers: whether every scenario replayed the same, one line and one result per scenario. */
export interface Regression {
  ok: boolean;
  lines: string[];
  results: Replayed[];
}

/** Replay every scenario with its recorded stubs, under the profile `activeProfile` picks, and diff the report node by node. */
export async function regress(load: LoadResult, opts: { profile?: string } = {}): Promise<Regression> {
  const profile = activeProfile(load.registry.project?.doc, { flag: opts.profile, env: process.env });
  const stubbed = { seed: 0, profile, env: fakeEnvFor(load) };
  const emb = embedderFor(load, stubbed);
  const results: Replayed[] = [];
  const lines: string[] = [];
  for (const sc of load.registry.all('scenario')) {
    const trigger = load.registry.all('trigger').find(trigger => trigger.path === load.resolve(sc.doc.trigger));
    // S001 has already refused a scenario whose trigger is gone; skip rather than replay nothing.
    if (!trigger) {
      const gone = `names unknown trigger '${sc.doc.trigger}'`;
      results.push({ scenario: sc.path, same: false, diffs: [gone] });
      lines.push(`${sc.path}: ${gone}`);
      continue;
    }
    const report = sc.doc.cancelAt
      ? await cancelledReplay(load, stubbed, trigger.doc, sc.doc)
      : await emb.fire(trigger.doc, sc.doc.in, sc.doc.request ?? {}, { stubs: sc.doc.stubs });
    const diffs = diffOf(report, sc.doc.expect);
    results.push({ scenario: sc.path, same: diffs.length === 0, diffs });
    lines.push(`${sc.path}: ${diffs.length ? `DIFF ${diffs.join('; ')}` : 'same'}`);
  }
  return { ok: results.every(one => one.same), lines, results };
}

/**
 * A scenario that pins a cancellation, replayed: its `cancelAt` is taken out of the recorded stubs so the run reaches
 * that effect's stub, which aborts the run's signal there. A node, never a duration, so the replay is the same on
 * every machine; an embedder of its own, since the stub that aborts is this run's alone.
 */
function cancelledReplay(
  load: LoadResult,
  stubbed: { seed: number; profile?: string; env: NodeJS.ProcessEnv },
  trigger: TriggerDoc,
  sc: ScenarioDoc,
): Promise<Report> {
  const path = sc.cancelAt ?? '';
  const control = new AbortController();
  const emb = embedderFor(load, { ...stubbed, cancelAt: { path, abort: () => control.abort() } });
  const { [path]: _, ...stubs } = sc.stubs ?? {};
  return emb.fire(trigger, sc.in, sc.request ?? {}, { stubs, signal: control.signal });
}

function fakeEnvFor(load: LoadResult): NodeJS.ProcessEnv {
  const env: NodeJS.ProcessEnv = {};
  for (const name of Object.values(load.registry.project?.doc.secrets ?? {})) env[name] = `stub-${name.toLowerCase()}`;
  return env;
}
