/**
 * What `wilanis describe` and `wilanis ls` say of a scenario (RFC 0018): the way in it replays, the branch it proves,
 * how it expects the run to end and how each switch routed, and which command wrote it; and of a trigger, how many
 * scenarios replay it and who wrote them. The viewer reads the same words from here, so a page and the command
 * cannot say a scenario two ways.
 */
import { type Loaded, type ScenarioBranch, type ScenarioDoc, type Scope, stem } from '@wilanis/core';

/** A command that writes scenarios, by the `generated` mark it leaves on what it wrote. */
export type ScenarioWriter = NonNullable<ScenarioDoc['generated']>;

/** Who wrote a scenario: the command its `generated` names, or a person, where it names none. */
export type ScenarioAuthor = ScenarioWriter | 'hand';

/** Who writes scenarios, in the order a trigger's are counted and listed: the recorder, edges, fuzz, then a person. */
export const AUTHORS: readonly ScenarioAuthor[] = ['rehearse', 'edges', 'fuzz', 'hand'];

/** The command that writes each kind of generated scenario, in the words a line names it by. */
export const WRITTEN_BY: Record<ScenarioWriter, string> = {
  rehearse: 'wilanis rehearse --record',
  edges: 'wilanis fuzz --edges',
  fuzz: 'wilanis fuzz',
};

/** The sentence `describe` and the viewer mark a generated scenario with; nothing for one written by hand. */
export function generatedSaid(doc: ScenarioDoc): string | undefined {
  return doc.generated ? `generated by ${WRITTEN_BY[doc.generated]}: regenerate, do not edit` : undefined;
}

/** What `wilanis ls` puts after a scenario's path: the command that wrote it, `(rehearse)`, `(edges)` or `(fuzz)`. */
export function writtenMark(file: Loaded): string {
  const generated = file.kind === 'scenario' ? (file.doc as ScenarioDoc).generated : undefined;
  return generated ? `  (${generated})` : '';
}

/**
 * The decision a scenario proves, in words: `get-row 'route' when status == 404 → missing`. The else is `otherwise`,
 * as the recorded file's description says it.
 */
export function provesSaid(branch: ScenarioBranch): string {
  const rule = branch.when === 'else' ? 'otherwise' : `when ${branch.when}`;
  return `${stem(branch.graph)} '${branch.node}' ${rule} → ${branch.to}`;
}

/** How a scenario expects its run to end: `done`, `failed as missing` for a declared refusal, or `unreachable -- <why>`. */
export function expectsSaid(expect: ScenarioDoc['expect']): string {
  if (expect.status === 'unreachable')
    return expect.unreachable ? `unreachable -- ${expect.unreachable}` : 'unreachable';
  return expect.reason === undefined ? expect.status : `${expect.status} as ${expect.reason}`;
}

/** How the recorded run routed: a line per node with a `selected`, `op.route → missing`, in the order it was recorded. */
function routedLines(expect: ScenarioDoc['expect']): string[] {
  return Object.entries(expect.nodes ?? {}).flatMap(([id, node]) =>
    node.selected === undefined ? [] : [`    ${id} → ${node.selected}`],
  );
}

/** What a policy scenario fires, said beside the policy. */
const IN_PLACE = "its decide, fired under the trigger's kind in place of the trigger's fire";

/**
 * A scenario: the trigger it drives, and the policy whose decision it fires in the trigger's place; the branch it
 * proves; the seed; how it expects the run to end, and under that how each switch routed, since the routing is what
 * a reader came for; and, for one a command wrote, that command, which rewrites it.
 */
export function scenarioLines(doc: Loaded): string[] {
  const declared = doc.doc as ScenarioDoc;
  const generated = generatedSaid(declared);
  return [
    `drives  ${declared.trigger}`,
    ...(declared.policy ? [`policy  ${declared.policy}  (${IN_PLACE})`] : []),
    ...(declared.branch ? [`proves  ${provesSaid(declared.branch)}`] : []),
    `seed    ${declared.seed}`,
    `expects ${expectsSaid(declared.expect)}`,
    ...routedLines(declared.expect),
    ...(generated ? [generated] : []),
  ];
}

/** The scenarios replaying one trigger's fire, by who wrote them, each in path order. */
export type TriggerScenarios = Record<ScenarioAuthor, Loaded<ScenarioDoc>[]>;

/**
 * The scenarios that replay one trigger's fire, grouped by who wrote them as `wilanis ls` marks them: recorded,
 * edges, fuzzed, by hand. One replaying a policy's decision under the trigger is the policy's -- recorded under the
 * policy's directory, once, whichever attaching trigger lends it a kind -- so it is not among what the trigger carries.
 */
export function scenariosOf(trigger: { path: string }, scope: Scope): TriggerScenarios {
  const by: TriggerScenarios = { rehearse: [], edges: [], fuzz: [], hand: [] };
  const replaying = scope.registry
    .all('scenario')
    .filter(one => !one.doc.policy && scope.canon(one.doc.trigger) === trigger.path)
    .sort((one, other) => one.path.localeCompare(other.path));
  for (const one of replaying) by[one.doc.generated ?? 'hand'].push(one);
  return by;
}

/** The directory one scenario sits in, below the root, as `--record` names the directory it wrote. */
const dirOf = (one: Loaded) => one.path.replace(/^@/, '').replace(/\/[^/]*$/, '');

/**
 * What a trigger carries in scenarios, said after its policies: how many were recorded, are edges, were fuzzed and
 * were written by hand, and the directories they sit in, so the branches a trigger carries are one command away.
 */
export function triggerScenarioLines(trigger: Loaded, scope: Scope): string[] {
  const by = scenariosOf(trigger, scope);
  const all = Object.values(by).flat();
  if (!all.length)
    return [
      'scenarios  none yet -- wilanis rehearse --record writes one per branch, wilanis fuzz --edges one per input edge',
    ];
  const fuzzed = by.fuzz.length ? [`${by.fuzz.length} fuzzed`] : [];
  const counts = [
    `${by.rehearse.length} recorded`,
    `${by.edges.length} edge(s)`,
    ...fuzzed,
    `${by.hand.length} by hand`,
  ];
  return [`scenarios  ${counts.join(', ')}`, ...[...new Set(all.map(dirOf))].map(dir => `    ${dir}/`)];
}
