#!/usr/bin/env bash
# The gate. Your work is accepted when every criterion below prints PASS.
#
#   bash accept.sh <METHOD> <ROUTE>        e.g.  bash accept.sh POST '/customers/{id}/active'
#
# METHOD and ROUTE are the endpoint you expose; ROUTE contains the literal {id}. The script judges the
# tree the way a reviewer would: it runs the checker and the rehearsal, reads what they say, starts the
# tree under the local profile, and drives the endpoint with curl. It never reads your documents to see
# how you did it, except to confirm that no rule a human wrote has changed in what it states.
# Do not edit this file. Read it: every criterion says what the endpoint must do.
set -uo pipefail
METHOD=${1:?METHOD}; ROUTE=${2:?ROUTE, with the literal id placeholder in braces}
cd "$(dirname "$0")"
PORT=$(node -e 'const p=require("./project.json");process.stdout.write(String(p.plugins.find(x=>x.use==="@http").settings.port))')
BASE=$(git rev-list --max-parents=0 HEAD)
H="http://localhost:$PORT"
LOG=$(mktemp -t accept)
pass=0; fail=0
ok()   { pass=$((pass+1)); printf 'PASS  %s\n' "$1"; }
bad()  { fail=$((fail+1)); printf 'FAIL  %s\n      expected: %s\n      got:      %s\n' "$1" "$2" "$(printf '%s' "$3" | head -c 300)"; }
check() { # check <name> <expected-description> <actual> <grep-pattern>
  if printf '%s' "$3" | grep -qE -- "$4"; then ok "$1"; else bad "$1" "$2" "$3"; fi
}
status() { curl -s -g -o /dev/null -w '%{http_code}' "$@"; }
body()   { curl -s -g --max-time 10 "$@"; }

echo "== The tree at rest"
CHECK=$(npx wilanis check . 2>&1 | tail -3)
check "1 wilanis check passes" "ok: N documents" "$CHECK" '^ok: [0-9]+ documents'
REH=$(npx wilanis rehearse . --profile local 2>&1)
check "2 every rehearsed branch settles" "every branch settled" "$(printf '%s' "$REH" | grep -E 'every branch settled|NEVER RUN|BROKE|BLOCKED' | head -3)" 'every branch settled'
printf 'INFO  3 the rehearsal says: %s  (the rule held at 5 triggers before your change; this line is reported, not judged)\n' "$(printf '%s' "$REH" | grep 'Writes are for registrars' | sed 's/^ *//')"
for inv in features/customers/domain/a-customer-is-reachable.invariant.json; do
  before=$(git show "$BASE:$inv" | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>process.stdout.write(JSON.parse(s).holds.when))')
  after=$(node -e 'process.stdout.write(require("./'"$inv"'").holds.when)')
  check "4 the rule in $(basename "$inv" .invariant.json) states what it stated" "$before" "$after" "^$(printf '%s' "$before" | sed 's/[][\.*^$|()+?{}\\]/\\&/g')\$"
done
before=$(git show "$BASE:features/customers/domain/writes-are-for-registrars.invariant.json" | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>process.stdout.write(JSON.parse(s).access.requires.policy))')
after=$(node -e 'process.stdout.write(require("./features/customers/domain/writes-are-for-registrars.invariant.json").access.requires.policy)')
check "5 the access rule still requires the same policy" "$before" "$after" "^$(printf '%s' "$before" | sed 's/[][\.*^$|()+?{}\\]/\\&/g')\$"

echo "== The tree serving"
# stop whatever listens on this tree's port and nothing else: other trees on this machine are not ours to kill
for pid in $(lsof -ti tcp:$PORT 2>/dev/null); do kill "$pid" 2>/dev/null; done; sleep 1
CUSTOMERS_JWT_SECRET=accept-secret CUSTOMERS_DATABASE_URL=postgres://unused npx wilanis start . --profile local > "$LOG" 2>&1 &
PID=$!
for i in $(seq 1 30); do grep -q "Listen: ok" "$LOG" && break; sleep 1; done
check "6 the tree starts and listens" "startup 7/7 Listen: ok" "$(grep -E 'Listen: ok|refused|missing' "$LOG" | head -2)" 'Listen: ok'
tok() { body -X POST $H/api/v1/auth-employees -H 'content-type: application/json' -d "{\"username\":\"$1\",\"password\":\"$1-pass\"}" | sed -n 's/.*"accessToken":"\([^"]*\)".*/\1/p'; }
BO=$(tok bo); CY=$(tok cy)
# signing in writes the session under .wilanis/ and the reload watcher sees it (wilanis-js#490); wait for
# both reloads, one per sign-in, before recording, or the memory store starts over under the calls below
for i in $(seq 1 8); do [ "$(grep -c '^reload: [0-9]' "$LOG")" -ge 2 ] && break; sleep 1; done; sleep 1
R() { printf '%s' "$ROUTE" | sed "s/{id}/$1/"; }
REC1=$(body -X POST $H/customers -H "authorization: Bearer $BO" -H 'content-type: application/json' -d '{"name":"Ada Lovelace","email":"ada@example.com","tier":"silver"}' -w '  [%{http_code}]')
REC2=$(body -X POST $H/customers -H "authorization: Bearer $BO" -H 'content-type: application/json' -d '{"name":"Grace Hopper","email":"grace@example.com","tier":"bronze"}' -w '  [%{http_code}]')
ADAID=$(printf '%s' "$REC1" | sed -n 's/.*"id":"\([^"]*\)".*/\1/p'); GRACEID=$(printf '%s' "$REC2" | sed -n 's/.*"id":"\([^"]*\)".*/\1/p')
check "7 two customers registered as bo, one silver and one bronze" "two 201 answers with ids" "$REC1 // $REC2" '^\{"id":"[^"]+".*\[201\] // \{"id":"[^"]+".*\[201\]$'

echo "== The endpoint"
r=$(body -X "$METHOD" "$H$(R "$ADAID")" -H "authorization: Bearer $BO" -w '  [%{http_code}]')
check "8 toggling a silver customer as bo answers 200 and shows active true" '{"id":...,"active":true}  [200]' "$r" '"active":true.*\[200\]$'
r=$(body -X "$METHOD" "$H$(R "$ADAID")" -H "authorization: Bearer $BO" -w '  [%{http_code}]')
check "9 toggling them again answers 200 and shows active false" '{"id":...,"active":false}  [200]' "$r" '"active":false.*\[200\]$'
r=$(body "$H/customers/$ADAID" -w '  [%{http_code}]')
check "10 reading the customer back shows their active field" '{"id":...,"active":false}  [200]' "$r" '"active":false.*\[200\]$'
r=$(body -X "$METHOD" "$H$(R "$GRACEID")" -H "authorization: Bearer $BO" -w '  [%{http_code}]')
check "11 toggling the bronze customer as bo answers 200 and shows active true" '{"id":...,"tier":"bronze",...,"active":true}  [200]' "$r" '"active":true.*\[200\]$'
r=$(body "$H/customers/$GRACEID" -w '  [%{http_code}]')
check "12 the bronze customer reads back active" '{"id":...,"active":true}  [200]' "$r" '"active":true.*\[200\]$'
r=$(body "$H/customers" -w '  [%{http_code}]')
check "13 the list still answers 200 with both customers" '[{...},{...}]  [200]' "$r" "$ADAID.*$GRACEID.*\[200\]$|$GRACEID.*$ADAID.*\[200\]$"
r=$(body -X "$METHOD" "$H$(R "$ADAID")" -H "authorization: Bearer $CY" -w '  [%{http_code}]')
check "14 cy, an employee without the registrar role, is refused 403 forbidden" '{"reason":"forbidden",...}  [403]' "$r" '"reason":"forbidden".*\[403\]$'
r=$(body -X "$METHOD" "$H$(R "$ADAID")" -w '  [%{http_code}]')
check "15 no token is refused 401 anonymous" '{"reason":"anonymous",...}  [401]' "$r" '"reason":"anonymous".*\[401\]$'
r=$(body -X "$METHOD" "$H$(R nope)" -H "authorization: Bearer $BO" -w '  [%{http_code}]')
check "16 an unknown id is refused 404 missing" '{"reason":"missing",...}  [404]' "$r" '"reason":"missing".*\[404\]$'
r=$(body -X "$METHOD" "$H$(R "$ADAID")" -H "authorization: Bearer $BO" -w '  [%{http_code}]')
check "17 a third toggle activates the silver customer again" '{"id":...,"active":true}  [200]' "$r" '"active":true.*\[200\]$'
r=$(body "$H/customers.csv" -H "authorization: Bearer $BO")
check "18 the export carries the flag: the silver customer's row ends in true" "$ADAID,...,true" "$(printf '%s' "$r" | grep "$ADAID")" "^$ADAID,.*,true\s*$"

kill $PID 2>/dev/null; wait $PID 2>/dev/null
echo "== Verdict"
if [ "$fail" -eq 0 ]; then echo "ACCEPTED  $pass criteria pass"; exit 0; else echo "REJECTED  $fail of $((pass+fail)) criteria fail"; exit 1; fi
